[sources.in]
type = "stdin"

[sinks.my_http_sink]
inputs = ["in"]
type = "http"
encoding.codec = "text"
uri = "https://test-livelogs.search.windows.net/indexes/hotels-quickstart/docs/index?api-version=2020-06-30"
method = "post"

[sinks.my_http_sink.headers]
    Content-Type = "application/json"
    api-key = "kUOiCN7aiOWVv8cNuEIQe5Nxbr5b5PkQOk72VTbVOlAzSeBbNlGy"
